### ISSUE TITLE
How to manualy deserialize .mca files?

### ISSUE THREAD

**Issue by jotalanusse** [owengage/fastnbt#100]
I would like to know if it is possible to manually deserialize `.mca` files, similar to what is done with the `level.dat` in these examples:

[nbt-dump.rs](https://github.com/owengage/fastnbt/blob/master/fastnbt/examples/nbt-dump.rs)
[simple-deserialize.rs](https://github.com/owengage/fastnbt/blob/master/fastnbt/examples/simple-deserialize.rs)

I know that `level.dat` files are compressed with Gzip, and `.mca` files with Zlib, but I don't know how I should approach the parsing process.

Any help is greatly appreciated!

**Comment by owengage** [comment]
Hi, you should check out the Region struct in fastanvil. That will let you
extract chunks, which you can then read as NBT.

**Comment by jotalanusse** [comment]
There is a function `region.read_chunk()` that returns a `Vec<u8>`. Is this the raw NBT data?

**Comment by owengage** [comment]
Yes it is, uncompressed. You can see the docs here: https://docs.rs/fastanvil/latest/fastanvil/struct.Region.html#method.read_chunk
