### ISSUE TITLE
Compatibility with `serde_path_to_error`

### ISSUE THREAD

**Issue by AndrewKvalheim** [owengage/fastnbt#117]
I’d like to use [`serde_path_to_error`](https://crates.io/crates/serde_path_to_error) but don’t see how to acquire the prerequisite [`fastnbt::de::Deserializer`](https://docs.rs/fastnbt/2.5.0/fastnbt/de/struct.Deserializer.html):

```console
error: type `fastnbt::input::Slice<'_>` is private
|
|  let mut deserializer = fastnbt::de::Deserializer::from_bytes(&bytes, fastnbt::DeOpts::default());
|                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ private type
```

Should `fastnbt::de::Deserializer::from_bytes` be usable?

**Comment by owengage** [comment]
Hi, yes it looks like the slice type should be public. I'll look into this soon.
