### ISSUE TITLE
wasm_bindgen(start)

### ISSUE THREAD

**Issue by orsenkucher** [owengage/fastnbt#12]
You can probably mark it as `#[wasm_bindgen(start)]`, thus no invocation on js side required

https://github.com/owengage/fastnbt/blob/a1fa396bd34a53f6b49edcb85590df9e2af8e788/anvil-wasm/src/lib.rs#L91

**Comment by owengage** [comment]
Just tried this and it led to a problem I've seen a bunch of times that I can't figure out. I get this error from the worker bundles:

```
ReferenceError: can't access lexical declaration '__wbg_new_59cb74e423758ede' before initialization
```
I did find a Github issue that was talking about circular dependencies being involved. If I don't call `force_init` I get this error, with your suggestion or not.

If you have any insight into what might be causing it that would be fantastic.
