### ISSUE TITLE
[Feature Request] Allow deserialize into fastnbt::Value

### ISSUE THREAD

**Issue by Badel2** [owengage/fastnbt#19]
Sometimes I want to deserialize some field that I do not know the type of. For example, a compound tag with unknown fields. I tried to deserialize it as `struct Entity { fields: HashMap<String, Value> }`, but that doesn't work because `Value` does not implement `Deserialize`. I tried that because it works with `serde_json::Value`:

https://docs.serde.rs/serde_json/value/enum.Value.html

I don't know if `fastnbt::Value` is the right type for this use case, maybe something `fastnbt::Compound` would make more sense for my use case.

**Comment by owengage** [comment]
As it stands this isn't supported. The `Value` type is part of the `Parser` set of types which is not really involved with the serde deserializer.

What you're describing is probably what I'd have expected as well if I was seeing this for the first time, so I'll probably implement this at some point.

**Comment by Badel2** [comment]
Sure, so in the `Level` struct there is a field `TileEntities` which is a list of compond tags.

```rust
struct Level {
    // Other fields...
    #[serde(rename = "TileEntities")]
    tile_entities: Vec<TileEntity>,
}
```

But there are multiple types of `TileEntity`, so I don't know how to represent them as a struct. So I want to see the format of some of them, because the available fields change according to the "id" field. With serde_json I would do something like this:

```rust
struct TileEntity {
    id: String,
    #[serde(flatten)]
    other_fields: HashMap<String, Value>,
}
```

And then access the other fields as `for (k, v) in tile_entity.other_fields.iter() {}`.

But I don't know if `flatten` is possible to implement, so instead of `TileEntity` I could use a `HashMap`:

```rust
struct Level {
    // Other fields...
    #[serde(rename = "TileEntities")]
    tile_entities: Vec<HashMap<String, Value>>,
}
```

Or even a generic `Value`:

```rust
struct Level {
    // Other fields...
    #[serde(rename = "TileEntities")]
    tile_entities: Vec<Value>,
}
```

So I guess that what I really need is a way to enumerate all the fields of a `CompoundTag`. So maybe it's easier to implement a generic `CompoundTag` instead of a generic `Value`.

That being said, my solution was to use a different library that provides this functionality: https://github.com/eihwaz/named-binary-tag

I can use that library to enumerate all the fields, write the struct definitions using optional fields (and only using the fields that I'm interested in), and then use this library to deserialize them. Also I could use an online NBT viewer but the one I was using does not support reading region files... What do you use for debugging?

**Comment by owengage** [comment]
So for looking at raw nbt I use the Parser type in fastnbt. The example
directories in fastanvil/fastnbt have some "dump" examples.

But yeah that makes sense. I'll keep that use in mind while getting it
working.

**Comment by owengage** [comment]
@Badel2 `fastnbt::Value` should now work as you originally expected it to in fastnbt 0.12. Let me know if it doesn't :)

**Comment by owengage** [comment]
I'll be adding this to the documentation soon, but thought I'd drop this here. You can deserialize entities with a type like this:

```rust
#[derive(Deserialize, Debug)]
#[serde(tag = "id")]
enum Entity {
   #[serde(rename = "minecraft:bat")]
   Bat {
       #[serde(rename = "BatFlags")]
       bat_flags: i8,
   },

   #[serde(rename = "minecraft:creeper")]
   Creeper { ignited: i8 },

   // Entities we haven't coded end up as just 'unknown'.
   #[serde(other)]
   Unknown,
}
```
If you want to capture entities that you don't know as well with this, it gets a little more complicated and you need to wrap the tagged enum in an untagged enum:

```rust
#[derive(Deserialize, Debug)]
#[serde(untagged)]
enum Entity {
    Known(KnownEntity),
    Unknown(Value),
}
#[derive(Deserialize, Debug)]
#[serde(tag = "id")]
enum KnownEntity {
    #[serde(rename = "minecraft:bat")]
    Bat {
        #[serde(rename = "BatFlags")]
        bat_flags: i8,
    },
    #[serde(rename = "minecraft:creeper")]
    Creeper { ignited: i8 },
}
```
