### ISSUE TITLE
Serializer

### ISSUE THREAD

**Issue by owengage** [owengage/fastnbt#32]
Writing a serializer isn't high on my TODO list, but it's on it.

Feel free to like/comment this issue if it's something you would like to see.

**Comment by GrizzlT** [comment]
I would be particularly interested in said serializer. If I can help in any way, please let me now!

**Comment by owengage** [comment]
I happened to start in this recently! Not sure when I'll get around to completing it though, holidays and all. :)

**Comment by GrizzlT** [comment]
I might be interested in helping to speed up this development branch as I am starting to need a serializer rather soon. Can I contact you on discord for a discussion perhaps (my tag is GrizzlT#4595)? @owengage

**Comment by owengage** [comment]
@GrizzlT the branch dev/serializer (commit e00417f8a0df8a3787ce9a8dfd8a6d9f82fe4ffc) has a mostly complete serializer on it. There's the more obscure Rust types it doesn't yet serialize but I think it covers a lot at the moment.

Do you think you can test it out at all? Or are you needing snbt support for what you're doing?

**Comment by GrizzlT** [comment]
When I have some time on my hands I'll definitely try this out!!

As you might know, chunk packets contain a heightmap encoded in NBT-format. That will be my first case to test it on.

**Comment by RubixDev** [comment]
The current serializer in version `2.0.0-alpha` is working for me in [rustmatica](https://github.com/RubixDev/rustmatica). Would appreciate it being in a stable release soon

**Comment by owengage** [comment]
fastnbt-2.0.0 is now available. Thank you for testing it out folks. :)
