### ISSUE TITLE
Array types in untagged enums: data did not match any variant of untagged enum

### ISSUE THREAD

**Issue by ValentiMS** [owengage/fastnbt#55]
fastnbt fails to deserialize untagged enums with structs containing array types like `fastnbt::ByteArray` or `fastnbt::LongArray`. 
```rust
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize)]
struct A {
    val: fastnbt::LongArray,
}

#[derive(Serialize, Deserialize)]
struct B;

#[derive(Serialize, Deserialize)]
#[serde(untagged)]
enum C {
    A(A),
    B(B)
}

fn main() {
    let C = C::A(A { val: fastnbt::LongArray::new(Vec::new()) });
    let ser = fastnbt::to_bytes(&C).unwrap();

    let _: C = fastnbt::from_bytes(&ser).unwrap();
}
```
The program works as expected when deserializing directly to struct `A`.

**Comment by owengage** [comment]
[This is documented](https://docs.rs/fastnbt/latest/fastnbt/index.html#byte-int-and-long-array-types), but does say to open an issue if it's important to you.

This is something I will eventually look into. v1 of fastnbt supports this if all you need is deserialization. If you also need serialization then you might need to work around it somehow. The hacky way that fastanvil currently does it is by [trying one then the other](https://github.com/owengage/fastnbt/blob/master/fastanvil/src/java/mod.rs#L43-L50)...

**Comment by ValentiMS** [comment]
Thanks for the solution! However, my case requires the enum to be inside a struct, ie
```rust
#[derive(Serialize, Deserialize)]
struct A {
    val: fastnbt::LongArray,
}

#[derive(Serialize, Deserialize)]
struct B;

#[derive(Serialize, Deserialize)]
#[serde(untagged)]
enum C {
    A(A),
    B(B)
}

#[derive(Serialize, Deserialize)]
struct D {
 inner: C,
 #[serde(flatten)]
 extra: HashMap<String, fastnbt::Value>
}
```
Is there any hack to work around this issue?

**Comment by owengage** [comment]
Untagged is now supported in fastnbt 2.3.0. Sorry it took so long to get back to you!
