### ISSUE TITLE
fastanvil : allow writing maps

### ISSUE THREAD

**Issue by nicoxxl** [owengage/fastnbt#68]
`fastanvil` allow for reading maps but not writing.

It would be nice that it could.

-----

Before edit :  
> # RegionLoader should be able to create **Regions**
> 
> The `RegionLoader` trait is good to read maps but not to create them.
> 
> It would be nice to have a way to create empty regions, on either the `RegionLoader` trait or some `RegionCreater` extension trait.

**Comment by owengage** [comment]
Hi @nicoxxl, does the `fastanvil::Region` struct not allow what you need? 

You can create a new region with that and write chunks to it. It doesn't help you create chunks though. fastanvil doesn't contain a writable chunk type (it doesn't deserialize entities for example), you'd have to make that struct yourself.
