### ISSUE TITLE
WASM compilation

### ISSUE THREAD

**Issue by SirWindfield** [owengage/fastnbt#7]
I wanted to parse structure files in one of my projects. Skimming through the library it doesn't seem to be that easy to convert it to `no_std`. The parsing uses pure `Vec`s at some places, `println` is used for errors outputs.

Did you have something specific in mind for allowing WASM compilation? Or is that just a big TODO that involves some larger refactoring?

**Comment by owengage** [comment]
Hi SirWindfield,

I happen to have been working compiling to WASM recently. Check out the [dev/server](https://github.com/owengage/fastnbt/tree/dev/server) branch. WASM doesn't require no-std (though I imagine it does add some bloat to the output WASM, but in this case it all became about 1.2 MiB which isn't much for what it's doing).

You can see it in action here: [https://owengage.com/anvil/](https://owengage.com/anvil/)

**Comment by owengage** [comment]
I've just updated master to include this, and published 0.9 for any of the fixes I made to make WASM work (I recall tweaking how regions were loaded, as it used File).

Out of curiosity, what's the project?

**Comment by SirWindfield** [comment]
I always thought that WASM does naturally need `no_std`, as stuff like `fs` isn't available anyawy.

It's part of a data pack I am developing that spawns in custom structures using the 1.16 experimental worldgen configurations. I've written a simple static website that is hosted on Vercel. People can login using their GitHub account and submit new structures to get included if they want. The structure file and a render is saved to a Gist and a new issue is created with a template and a link to the rendered structure and the structure file.

I wanted to write the rendering part using WebGL and since Rust is my favorite language by far and it can compile to WASM, I wanted to give it a try and use it :)

**Comment by owengage** [comment]
I'm not familiar with the details, but I think somewhere for wasm the standard library is implemented mostly with panics and errors as implementations for things like file io.

It definitely compiles and works for wasm using wasm-pack. If you find anything to block you in your project let me know! 

And it could definitely be smaller, but I was expecting something far more rediculous like 20+, so for now I'm not too focused on the size.

**Comment by owengage** [comment]
Created #11 to cover this.
