### ISSUE TITLE
Delete/Remove chunk

### ISSUE THREAD

**Issue by icrayix** [owengage/fastnbt#72]
What about adding a feature to remove a chunk from a Region?

**Comment by owengage** [comment]
That should be a relatively vely straight forward thing to add. I believe Minecraft recreates a chunk if it finds it missing from the region file, so sounds like an operation people would find useful.

**Comment by icrayix** [comment]
Started implementing this in #76

**Comment by owengage** [comment]
Released in fastanvil-0.27.0. :)
