### ISSUE TITLE
128-bit deserialization support went missing

### ISSUE THREAD

**Issue by RubixDev** [owengage/fastnbt#74]
Almost one year ago in #53 I added support for (de)serializing 128-bit integers as IntArrays with 4 elements which is used by Minecraft to store UUIDs. Today I updated my fastnbt dependency and noticed the support for deserializing `u128` and `i128` types seems to have been removed, whilst still being mentioned in the docs for the `fastnbt::de` module. This, together with the fact that serialization is still supported, leads me to believe this was done by mistake when switching to `de2` in 2ae694398c25054ce56c40afa12cc65f4f9d5dcd.

Edit: version 2.2 seems to be the only version supporting the deserialization

**Comment by owengage** [comment]
Definite mistake, sorry about that. I was certain that was unit tested, I must have missed a few in the transition.

I'll look into it next chance I get.

**Comment by RubixDev** [comment]
Mistakes happen :shrug:. It was unit tested before, but that test was removed in the same commit

**Comment by owengage** [comment]
Fixed in fastnbt 2.4.3 and master.
