### ISSUE TITLE
Fastanvil image feature flag

### ISSUE THREAD

**Issue by icrayix** [owengage/fastnbt#77]
Hi,

looking at fastanvils dependency tree (`cargo tree`) shows that a lot of dependencies are sub-dependencies of the image crate.
That is even though I do not use any features related to rendering the world, etc.

Is there any chance we can factor out all image related features into a feature flag in order to reduce the amount of overhead for people that do not use it?

**Comment by owengage** [comment]
This sounds like a good idea to me. I believe flags can be named after crates now, so an image feature that is default would be good.

Since fastanvil is pre1.0 I'm not too worried about breaking changes, but I don't think this will introduce any.

**Comment by owengage** [comment]
Published fastanvil-0.28.0. :)
