### ISSUE TITLE
Panic on `fastanvil::Region::remove_chunk` for a non-existing chunk

### ISSUE THREAD

**Issue by Nemo157** [owengage/fastnbt#90]
```
Message:  called `Result::unwrap()` on an `Err` value: 0
Location: cargo\registry\src\index.crates.io-6f17d22bba15001f\fastanvil-0.28.0\src\region.rs:329
```

I'm guessing it should be checking if the location is `0, 0` already and then just returning.

**Comment by owengage** [comment]
Hi there @Nemo157. I'm currently on vacation/holiday so won't be getting around to looking at this for a few weeks. Sorry you ran into issues!

**Comment by Nemo157** [comment]
Don't worry, these crates have been such a help setting up some tooling for a server. I'll probably submit a PR soon to fix it whenever you get time to review it.
