### ISSUE TITLE
TopShadeRenderer::render returns only transparent on forge chunks

### ISSUE THREAD

**Issue by suppergerrie2** [owengage/fastnbt#92]
`TopShadeRenderer::render` assumes forge chunks are not fully generated because the status is `minecraft:full` instead of `full` as the code assumes:
https://github.com/owengage/fastnbt/blob/8ad72ab3a20e50b921ec14ea2a4cedf82bf24200/fastanvil/src/render.rs#L35-L43

An example region file (generated with Minecraft Forge 47.1.0) that only renders transparent: [r.0.0.zip](https://github.com/owengage/fastnbt/files/12284697/r.0.0.zip)

**Comment by owengage** [comment]
Thank you for the example data! That's interesting, I'd like to understand why forge makes the status like this rather than the way vanilla seems to. Looks like it's a simple fix though. I will get around to it. :)

**Comment by suppergerrie2** [comment]
I'm assuming it is because mods could technically add their own status? I made a local fork to just add 4 more values but with "minecraft:" prefixed and it works fine (other than pink for some unsupported blocks but that was to be expected!)
